### ISSUE TITLE
Facebook language

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach-chatbot#8] opened 2017-12-05 01:24 UTC
![image](https://user-images.githubusercontent.com/25951555/33585219-1c82484e-d99e-11e7-8fd3-3a994fff5eb7.png)

## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:
  - Platform:

**Comment by matthewberryman** [comment] 2017-12-07 06:41
Duplicate of https://github.com/MSFREACH/msf-reach-chatbot/issues/5

**Comment by matthewberryman** [comment] 2017-12-07 06:41
The language is core functionality, and will be the same across all social media

**Closed by matthewberryman** 2017-12-07 06:41 UTC
