### ISSUE TITLE
Automating addition of new event

### ISSUE THREAD

**Issue by LucieGueuning** [MSFREACH/msf-reach-chatbot#14] opened 2018-01-19 12:31 UTC
## Steps to Reproduce the Problem

  1.
  2.
  3.

## Specifications

  - Version:
  - Platform:

**Comment by LucieGueuning** [comment] 2018-01-19 12:31
I’ve just got some new code up today in our dev environment https://dev.msf-reach.org/ that is now automatically adding entries into the chatbot for new and modified events (as they are modified going forwards) and just tried this out then successfully over the Twitter version of the bot (ignore the duplicate reply that is an unrelated known bug in the Twitter code elsewhere).

I still need to write a script to go back and add old events into the system and I’ll let you know when that’s done.

Tom—I will need to get you some configuration details for you to run with this locally (it’s off by default if you don’t have them), which I will do later today.

**Comment by matthewberryman** [comment] 2018-01-21 21:26
Duplicate of https://github.com/MSFREACH/msf-reach-chatbot/issues/6

**Closed by matthewberryman** 2018-01-21 21:26 UTC
